name: Non regression tests for TimedPetriNetEditor
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  non_regression_linux:
    name: Non regression tests on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install libdw-dev pkg-config libmosquitto-dev libx11-dev libxinerama-dev
          sudo apt-get install libasound2-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev
          sudo apt-get install libwayland-dev libxkbcommon-x11-dev libglfw3-dev libxcursor-dev libxinerama-dev
      - name: Checkout TimedPetriNetEditor
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compile TimedPetriNetEditor
        run: |
          make download-external-libs
          make compile-external-libs
          make -j`nproc --all`
          sudo make install
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Do non regression tests
        run: |
          cd tests
          make -j`nproc --all`
          ./build/TimedPetriNetEditor-UnitTest
      - name: Check if the library can be linked against a project
        run: |
          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
          cd LinkAgainstMyLibs/TimedPetriNetEditor
          make -j`nproc --all`
          ./build/TimedPetriNetEditor

  non_regression_macos:
    name: Non regression tests on MacOS X
    runs-on: macos-latest
    steps:
      - name: Install system packages
        run: |
          brew install pkg-config mosquitto raylib glfw glew
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compile TimedPetriNetEditor
        run: |
          make download-external-libs
          make compile-external-libs
          make -j`sysctl -n hw.logicalcpu`
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Do non regression tests
        run: |
          cd tests
          make -j`sysctl -n hw.logicalcpu`
          ./build/TimedPetriNetEditor-UnitTest
      - name: Create the DMG file
        run: |
          hdiutil create -format UDZO -srcfolder build/TimedPetriNetEditor.app build/TimedPetriNetEditor.dmg
      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: TimedPetriNetEditor-macos
          path: build/TimedPetriNetEditor.dmg
